export const PUT_ACCEPT_OFFER_PENDING = "PUT_ACCEPT_OFFER_PENDING";
export const PUT_ACCEPT_OFFER_SUCCESS = "PUT_ACCEPT_OFFER_SUCCESS";
export const PUT_ACCEPT_OFFER_ERROR = "PUT_ACCEPT_OFFER_ERROR";
