export const DELETE_CANCEL_OFFER_PENDING = "DELETE_CANCEL_OFFER_PENDING";
export const DELETE_CANCEL_OFFER_SUCCESS = "DELETE_CANCEL_OFFER_SUCCESS";
export const DELETE_CANCEL_OFFER_ERROR = "DELETE_CANCEL_OFFER_ERROR";
