export const POST_CREATE_PRODUCT_PENDING = "POST_CREATE_PRODUCT_PENDING";
export const POST_CREATE_PRODUCT_SUCCESS = "POST_CREATE_PRODUCT_SUCCESS";
export const POST_CREATE_PRODUCT_ERROR = "POST_CREATE_PRODUCT_ERROR";