export const POST_OFFER_PENDING = "POST_OFFER_PENDING";
export const POST_OFFER_SUCCESS = "POST_OFFER_SUCCESS";
export const POST_OFFER_ERROR = "POST_OFFER_ERROR";
export const POST_OFFER_INITIAL = "POST_OFFER_INITIAL";