export const GET_PRODUCT_DETAILS_PENDING = "GET_PRODUCT_DETAILS_PENDING";
export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS";
export const GET_PRODUCT_DETAILS_ERROR = "GET_PRODUCT_DETAILS_ERROR";
export const GET_PRODUCT_DETAILS_INITIAL = "GET_PRODUCT_DETAILS_INITIAL";