export const PUT_PURCHASE_PENDING = "PUT_PURCHASE_PENDING";
export const PUT_PURCHASE_SUCCESS = "PUT_PURCHASE_SUCCESS";
export const PUT_PURCHASE_ERROR = "PUT_PURCHASE_ERROR";
export const PUT_PURCHASE_INITIAL = "PUT_PURCHASE_INITIAL";
