export const GET_RECEIVED_OFFERS_PENDING = "GET_RECEIVED_OFFERS_PENDING";
export const GET_RECEIVED_OFFERS_SUCCESS = "GET_RECEIVED_OFFERS_SUCCESS";
export const GET_RECEIVED_OFFERS_ERROR = "GET_RECEIVED_OFFERS_ERROR";