export const POST_REJECT_OFFER_PENDING = "POST_REJECT_OFFER_PENDING";
export const POST_REJECT_OFFER_SUCCESS = "POST_REJECT_OFFER_SUCCESS";
export const POST_REJECT_OFFER_ERROR = "POST_REJECT_OFFER_ERROR";
