export const POST_UPLOAD_IMAGE_PENDING = "POST_UPLOAD_IMAGE_PENDING";
export const POST_UPLOAD_IMAGE_SUCCESS = "POST_UPLOAD_IMAGE_SUCCESS";
export const POST_UPLOAD_IMAGE_ERROR = "POST_UPLOAD_IMAGE_ERROR";
export const POST_UPLOAD_IMAGE_INITIAL = "POST_UPLOAD_IMAGE_INITIAL";
